In [2]:
import pandas as pd
df = pd.read_csv('iris.csv')

how big is the data

In [3]:
df.shape

(150, 5)

In [ ]:
how does data look like

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df.sample(5)

    sepal_length  sepal_width  petal_length  petal_width     species
40           5.0          3.5           1.3          0.3      setosa
8            4.4          2.9           1.4          0.2      setosa
92           5.8          2.6           4.0          1.2  versicolor
63           6.1          2.9           4.7          1.4  versicolor
38           4.4          3.0           1.3          0.2      setosa

3. data type of the columns

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

are there any missing values

In [8]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

how does data look mathematically

In [9]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

duplicates?

In [11]:
df.duplicated().sum()

np.int64(1)

correlation between columns 
range is between -1 and 1 
and the correlation pearsons value is represented as 
negative if theres negative correlation meaning if a feature goes up or down, other feature goes down as well 
positive if theres positive correlation meaning if a feature goes up, other feature goes up aswell

In [13]:
df.corr()['sepal_width']

ValueError: could not convert string to float: 'setosa'